### ISSUE TITLE
Does "MATCHES" work?

### ISSUE THREAD

**Issue by greatvovan** [asg017/sqlite-regex#7]
From the [documentation](https://github.com/asg017/sqlite-regex/blob/75e77ddad993477b4b05a3675f89c58c1ac6f822/README.md?plain=1#L15):

```sql
select 'foo' matches 'f';
```

The result is not shown, but if I try it, I experience the error:

```text
$ sqlite-tools-osx-x86-3410000/sqlite3
SQLite version 3.41.0 2023-02-21 18:09:37
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> .load ./regex0
sqlite> select 'foo' matches 'f';
Parse error: near "'f'": syntax error
  select 'foo' matches 'f';
                       ^--- error here
```

Is it supposed to work?

MacOS, official SQLite, latest everything.

**Comment by asg017** [comment]
My bad, that was a typo in the documentation. It has now been fixed, only the `REGEXP` operator works with that syntax (`select 'foo' regexp 'f';`), or any of the other functions listed in [`docs.md`](https://github.com/asg017/sqlite-regex/blob/main/docs.md)
